### PR TITLE
Correct Hadrian's Wall flavor text

### PR DESCRIPTION
**Pull request by SpencerDub**
Capitalize "his" in second sentence

### CODE REVIEW

**Comment by x3N1GM4x** [comment]
Good catch, thanks!

**Comment by x3N1GM4x** [comment]
Deployed to production.

**Comment by x3N1GM4x** [comment]
Hmm, strange - this one definitely deployed:

image

But I'm not seeing the change in the front end like I am for the Masvingo one which went in at the same time. Can anyone else confirm what they are seeing?

**Comment by SpencerDub** [comment]
It's live on the data for the original core, but if you view the data for Revised Core or System Core 2019, it doesn't show. That was my mistake.

**Pull request merged**
