### PR TITLE
deploy last fixes

### PR DESCRIPTION
**Pull request by Alsciende**

### CODE REVIEW

**Comment by gereons** [comment]
Just out of curiosity, when are these changes expected to show up in the nrdb API? https://netrunnerdb.com/api/2.0/public/cards?_locale=de still has the empty _locale block for UVC, while the "Clan" subtype for Salvaged Vanadis Armory is already visible.

**Comment by Alsciende** [comment]
The translations didn't update automatically. I updated it now. It should be live in ~10 minutes.

**Comment by gereons** [comment]
Thanks a lot!

**Comment by gereons** [comment]
Sorry, something seems to be off here - the _locale block is still empty.

**Comment by Alsciende** [comment]
The translation is databased though https://netrunnerdb.com/de/card/13038

**Comment by Alsciende** [comment]
I'll see what's going on

**Comment by gereons** [comment]
Thanks, your efforts are very much appreciated, as always!

**Comment by Alsciende** [comment]
Ok I busted the cache for that resource, it did the trick :)

**Pull request merged**
