### PR TITLE
Fix Hadrian's Wall flavor text capitalization

### PR DESCRIPTION
**Pull request by SpencerDub**
Fixed this in Original Core, but the issue was present in the Revised Core and System Core 2019 data too. This fixes Revised Core.

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
In the future, you can bundle as many fixes as you want into a single pr. We don't mind!

**Comment by SpencerDub** [comment]
@NoahTheDuke  - Oh, sorry! I am still very, very bad at understanding GitHub, so I haven't evolved beyond making single-file pull requests. Even that was a big step for me when I finally figured it out.

Next time I'm making a bunch of fixes across different files, I'll try to figure out how to bundle them to save y'all the hassle. Sorry again.

**Comment by NoahTheDuke** [comment]
No worries! I super appreciate all of the effort you've put in so far and look forward to all your contributions in the future.

**Comment by x3N1GM4x** [comment]
Deployed to production.

**Pull request merged**
