### PR TITLE
add spoilers

### PR DESCRIPTION
**Pull request by SuperFlamingTominoHead**

### CODE REVIEW

**Comment by SuperFlamingTominoHead** [comment]
Hmm, so the two first check pointed out the errors, but the last check doesn't, just says there's a formatting error? Could it be problems with tab/space?

**Comment by SuperFlamingTominoHead** [comment]
I guess it was...

**Comment by Alsciende** [comment]
@SuperFlamingTominoHead "NGO Front" is missing a faction_cost.

**Comment by gereons** [comment]
Fixed in #301

**Pull request merged**
