### PR TITLE
Updated to MWL 2.0

### PR DESCRIPTION
**Pull request by NoahTheDuke**
Modifies mwl.json to handle the new MWL 2.0 changes, as noted in #257.

I took the liberty of changing the "global_penalty" flag to be follow @yads's [comment](https://github.com/Alsciende/netrunner-cards-json/pull/208#issuecomment-293906340), set all of the Restricted cards to 3, and set all of the Removed cards to 0, under the idea that a number would denote how many of a given card can be included in a deck (leaving the Restricted exclusivity requirement to be implemented by each program, not by the data-set).

My changes are not and should not be final. I welcome all comments and suggestions on how to best modify this to fit our needs. Thankfully, the full list of cards has already been compiled, so all that would need changing is the penalty flag and the numbers.

### CODE REVIEW

**Comment by yads** [comment]
I guess I jinxed it :) I think it looks good. I'm wondering if maybe keeping the global_influence flag on the old MWLs as a deprecated field makes sense, depending how hard it is to update the existing code.

**Comment by yads** [comment]
Probably makes sense to keep it for backwards compatibility, but not have it in the 2.0 document.

**Comment by yads** [comment]
It also might be better to make the card values contain the card's status, rather than quantity. For example, in order to find restricted cards, the code would currently need to infer information about its status. Perhaps something more along the lines of:

```
{
  "03038":  "restricted",
  "08061": "banned",
  ...
}
```

Or even if we wanted to make it even more extensible:

```
{
  "03038":  { "type": "restricted" },
  "08061": { "type": "banned" },
  ...
}
```

**Comment by gereons** [comment]
I like the idea of marking types, but I'd rather not repeat it for every card. Why not invert the relationship, and have types with associated lists of cards?

```
{
  "restricted": [ "03038", ... ],
  "banned": [ "08061", ... ]
}
```

**Comment by Alsciende** [comment]
The MWL could overload parts of the cards.

MWL version 1.0 and 1.1 overload a new `global_penalty` property of some cards.

MWL version 1.2 overloads a new `universal_faction_cost` property of some cards.

MWL version 2.0 overloads the `deck_limit` property of some cards, and a new `is_restricted` property of some other cards.

Applying a MWL is overloading the cards data with the mwl data: `cardData = Object.assign(baseCardData, mwlCardData)`

Whether or not a MWL is active, the properties are always considered. The application of the deck legality rules is separated from the activation of a MWL.

**Comment by yads** [comment]
Ooh, I really like the idea of extending card properties based on the info in the MWL document. That way, like you said, you can look at the card data in whole, rather than looking in a bunch of different sources.

**Comment by NoahTheDuke** [comment]
I'm not into bike-shedding; I have no preference on how the data should be presented. Just let me know how y'all want it done, and I'll whip it up!

**Comment by Alsciende** [comment]
I'd like the data to look like

```
    {
        "cards": {
            "08061": {
                "deck_limit": 0
            },
            "03035": {
                "is_restricted": 1
            }
        },
        "code": "NAPD_MWL_2.0",
        "date_start": "2017-09-27",
        "name": "NAPD MWL 2.0"
    }
```

I'll store `cards` in a json array.

**Comment by NoahTheDuke** [comment]
Want this back-ported to the previous MWLs?

**Comment by Alsciende** [comment]
Yes. I don't think anyone is using that endpoint.

**Comment by NoahTheDuke** [comment]
Updated.

**Comment by jwarwick** [comment]
FWIW, jinteki.net uses that `mwl` endpoint. But we would need to make changes there to support new semantics anyway.

**Comment by jwarwick** [comment]
Found two errors in the file as I was working on the jinteki.net import:
1. Muertos Gang Member (08068) was swapped for Gang Sign (08067).
2. Rumor Mill (11022) was missing.

**Comment by Alsciende** [comment]
Thank you, @NoahTheDuke , it looks good.

@jwarwick would you prefer that I keep the /2.0/mwl endpoint untouched, and create a new endpoint for this new format?

**Comment by jwarwick** [comment]
@Alsciende - I've already updated the Jinteki code, so go ahead and modify the endpoint. When my last pull request goes through we should be compliant with both the `rotated` flag and the MWL changes. Thanks for getting all that updated.

**Comment by NoahTheDuke** [comment]
Updated.

**Pull request merged**
