### PR TITLE
Fix various typos and missing FT

### PR DESCRIPTION
**Pull request by SpencerDub**

### CODE REVIEW

**Comment by x3N1GM4x** [comment]
Hey @SpencerDub - looks like there's a merge conflict here - as if your changes to Neural EMP are being inserted into the middle of SEA Source for some reason.

Could you resolve this conflict and push again?

**Comment by NoahTheDuke** [comment]
Ah, the conflict probably happened when I rearraigned core2.

**Comment by x3N1GM4x** [comment]
[waves fist at @NoahTheDuke]

Shall I just push to this PR with a corrected core2.json then, if I've got a couple of minutes to burn?

**Comment by x3N1GM4x** [comment]
Aw jeez, what have I done now, lol.

Was trying to push a corrected core2.json to Spencer's master, expecting it to then appear against this PR. 🤦‍♂️

**Pull request closed without merging**
