### PR TITLE
added kitara cycle + sovereign sight previews

### PR DESCRIPTION
**Pull request by alexduryee**
Added information from https://www.fantasyflightgames.com/en/news/2017/9/11/sovereign-sight/.  It looks like Jinja City Grid and Friday Chip are from the next two packs (31 and 42, respectively), so they aren't included here.

### CODE REVIEW

**Comment by gereons** [comment]
Please change the cycle number to 21 so that Kitara gets sorted after the revised core set.

**Comment by gereons** [comment]
ss.json appears to contain a BOM, please remove. You can use the `validate.py` script in this repo to verify that all files are correctly formatted - it should report `Found 0 formatting and 0 validation errors`.

**Comment by alexduryee** [comment]
Thanks!  Should be resolved.

**Comment by gereons** [comment]
Thanks! There are a few more changes necessary before we can merge this, and those are the individual card codes. They need to start with "21" now as well, e.g. Lewi Guilherme needs to have "21005"

**Comment by gereons** [comment]
Thank you!

**Pull request merged**
