### PR TITLE
Update wording to match new printing

### PR DESCRIPTION
**Pull request by SpencerDub**
The new NISEI printing of Magnus Opus cards has brought new wording. This PR updates the card text to match the new wording.

### CODE REVIEW

**Comment by x3N1GM4x** [comment]
So are we just going to replace the existing Mopus set with updated wording, card images and set symbol? I thought the plan was to create it as a new set entirely and rotate the old one?

**Comment by NoahTheDuke** [comment]
Nah, just a stop gap while I deal with some life stuff and then I’ll undo this and publish the new set.

**Comment by x3N1GM4x** [comment]
Gotcha, sounds good. Let me know if you need me to deploy this to prod, looks like it's not there yet.

**Comment by x3N1GM4x** [comment]
Deployed to production.

**Pull request merged**
